jira_service_desk: Report Class Reference
Report Class Reference
Public Member Functions
__construct ()
getStatus ()
Protected Member Functions
checkExtensionConfiguration ()
checkServicedeskAvailability ()
Protected Attributes
$reports = []
$objectManager
$languageService
Detailed Description
Definition at line 12 of file Report.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Report constructor initializes the Objectmanager and the LanguageService.
Returns
void
Definition at line 40 of file Report.php.
     {
         $this->objectManager = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\ObjectManager::class);
         $this->languageService = $this->objectManager->get(\TYPO3\CMS\Core\Localization\LanguageService::class);
         $this->languageService->includeLLFile('EXT:jira_service_desk/Resources/Private/Language/locallang_report.xlf');
     }
Member Function Documentation
getStatus()
getStatus ()
Returns the status of an extension or (sub)system.
Returns
array
Exceptions
Definition at line 54 of file Report.php.
     {
         $this->reports = [];
         $pass = $this->checkExtensionConfiguration();
         if ($pass) {
             $this->checkServicedeskAvailability();
         }
         return $this->reports;
     }
References Report\$reports, Report\checkExtensionConfiguration(), and Report\checkServicedeskAvailability().
checkExtensionConfiguration()
checkExtensionConfiguration () protected
Check the extension configuration and add reports to report array.
Returns
bool
Definition at line 72 of file Report.php.
                                                      : bool
     {
         $extensionConfiguration = $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['jira_service_desk'];
         $pass = false;
         if ($extensionConfiguration['serviceDeskUrl']) {
             $pass = true;
         }
         $this->reports[] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Reports\Status::class,
             $this->languageService->getLL('report.check.serviceDeskUrl.title'),
             $pass ? 'OK' : 'Error',
             $pass ? '' : $this->languageService->getLL('report.check.serviceDeskUrl.description'),
             $pass ? \TYPO3\CMS\Reports\Status::OK : \TYPO3\CMS\Reports\Status::ERROR
         );
         $pass = false;
         if ($extensionConfiguration['serviceDeskId']) {
             $pass = true;
         }
         $this->reports[] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Reports\Status::class,
             $this->languageService->getLL('report.check.serviceDeskId.title'),
             $pass ? 'OK' : 'Error',
             $pass ? '' : $this->languageService->getLL('report.check.serviceDeskId.description'),
             $pass ? \TYPO3\CMS\Reports\Status::OK : \TYPO3\CMS\Reports\Status::ERROR
         );
         return $pass;
     }
Referenced by Report\getStatus().
checkServicedeskAvailability()
checkServicedeskAvailability () protected
Checks the service desk availability.
Returns
bool
Exceptions
Definition at line 107 of file Report.php.
                                                       : bool
     {
         $service = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Service::class)->initialize();
         $info = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\Info::class, $service)->getInfo();
         $pass = false;
         $msg = '';
         if ($info->status === 200) {
             $pass = true;
             $msg = 'Version: ' . $info->body->version . '<br>Platform: ' . $info->body->platformVersion . '<br>Build date: ' . $info->body->buildDate->friendly;
         }
         $this->reports[] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Reports\Status::class,
             $this->languageService->getLL('report.check.serviceDeskAvailability.title'),
             $pass ? 'OK' : 'Error',
             $pass ? $msg : $this->languageService->getLL('report.check.serviceDeskAvailability.description'),
             $pass ? \TYPO3\CMS\Reports\Status::OK : \TYPO3\CMS\Reports\Status::ERROR
         );
         return $pass;
     }
Referenced by Report\getStatus().
Field Documentation
$reports
$reports = [] protected
Definition at line 19 of file Report.php.
Referenced by Report\getStatus().
$objectManager
$objectManager protected
Definition at line 26 of file Report.php.
$languageService
$languageService protected
Definition at line 33 of file Report.php.
The documentation for this class was generated from the following file:
/Users/carsten.walther/Development/playground.dev.local/playground.git/typo3conf/ext/jira_service_desk/Classes/Reports/Report.php