jira_service_desk: ServiceDeskToolbarItem Class Reference
ServiceDeskToolbarItem Class Reference
Public Member Functions
checkAccess ()
getItem ()
hasDropDown ()
getDropDown ()
getAdditionalAttributes ()
getIndex ()
updateServiceDeskMenuHook (&$params)
Protected Member Functions
getFluidTemplateObject (string $filename)
Detailed Description
Definition at line 12 of file ServiceDeskToolbarItem.php.
Member Function Documentation
checkAccess()
checkAccess ()
Checks whether the user has access to this toolbar item.
Returns
bool TRUE if user has access, FALSE if not
Definition at line 19 of file ServiceDeskToolbarItem.php.
                                   : bool
     {
         return \Walther\JiraServiceDesk\Utility\AccessUtility::hasAccess();
     }
getItem()
getItem ()
Render "item" part of this toolbar.
Returns
string Toolbar item HTML
Exceptions
Definition at line 31 of file ServiceDeskToolbarItem.php.
                               : string
     {
         if (\Walther\JiraServiceDesk\Utility\AccessUtility::hasAccess()) {
             return $this->getFluidTemplateObject('ToolbarItem.html')->render();
         }
         return '';
     }
References ServiceDeskToolbarItem\getFluidTemplateObject().
hasDropDown()
hasDropDown ()
TRUE if this toolbar item has a collapsible drop down.
Returns
bool TRUE if there is a drop down, FALSE if not
Definition at line 45 of file ServiceDeskToolbarItem.php.
                                   : bool
     {
         if (\Walther\JiraServiceDesk\Utility\AccessUtility::hasAccess()) {
             return true;
         }
         return false;
     }
getDropDown()
getDropDown ()
Render "drop down" part of this toolbar.
Returns
string Drop down HTML
Exceptions
Definition at line 62 of file ServiceDeskToolbarItem.php.
                                   : string
     {
         if (\Walther\JiraServiceDesk\Utility\AccessUtility::hasAccess()) {
             $serviceDeskId = (int)$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['jira_service_desk']['serviceDeskId'];
             $service = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Service::class)->initialize();
             $serviceDesk = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\ServiceDesk::class, $service);
             $request = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\Request::class, $service);
             $customerRequests = $request->getCustomerRequests($serviceDeskId);
             $customerRequestCounts = [];
             if (is_array($customerRequests->body->values)) {
                 foreach ($customerRequests->body->values as $key => $customerRequest) {
                     $customerRequestCounts[$customerRequest->currentStatus->status]++;
                 }
             }
             $view = $this->getFluidTemplateObject('DropDown.html');
             $view->assignMultiple([
                 'serviceDesk' => $serviceDesk->getServiceDeskById($serviceDeskId),
                 'customerRequests' => array_sum($customerRequestCounts),
                 'customerRequestCounts' => $customerRequestCounts,
             ]);
             return $view->render();
         }
         return '';
     }
References ServiceDeskToolbarItem\getFluidTemplateObject().
getAdditionalAttributes()
getAdditionalAttributes ()
Returns an array with additional attributes added to containing tag of the item. Typical usages are additional css classes and data-* attributes, classes may be merged with other classes needed by the framework. Do NOT set an id attribute here.
array('class' => 'my-class', 'data-foo' => '42',)
Returns
array List item HTML attributes
Definition at line 105 of file ServiceDeskToolbarItem.php.
                                               : array
     {
         return [];
     }
getIndex()
getIndex ()
Returns an integer between 0 and 100 to determine the position of this item relative to others. By default, extensions should return 50 to be sorted between main core items and other items that should be on the very right.
Returns
int 0 .. 100
Definition at line 117 of file ServiceDeskToolbarItem.php.
                                : int
     {
         return 60;
     }
updateServiceDeskMenuHook()
updateServiceDeskMenuHook (& $params)
Called as a hook in \TYPO3\CMS\Backend\Utility\BackendUtility::getUpdateSignalCode, calls a JS function to change the number of opened documents
Parameters
$params
Definition at line 128 of file ServiceDeskToolbarItem.php.
                                                         : void
     {
         $params['JScode'] = '
             if (top && top.TYPO3.ServiceDeskMenu) {
                 top.TYPO3.ServiceDeskMenu.updateMenu();
             }
         ';
     }
getFluidTemplateObject()
getFluidTemplateObject (string $filename) protected
Returns a new standalone view, shorthand function.
Parameters
string $filename
Returns
\TYPO3\CMS\Fluid\View\StandaloneView The standalone view
Exceptions
Definition at line 145 of file ServiceDeskToolbarItem.php.
                                                                 : \TYPO3\CMS\Fluid\View\StandaloneView
     {
         $view = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Fluid\View\StandaloneView::class);
         $view->setLayoutRootPaths(['EXT:jira_service_desk/Resources/Private/Layouts']);
         $view->setPartialRootPaths(['EXT:jira_service_desk/Resources/Private/Partials']);
         $view->setTemplateRootPaths(['EXT:jira_service_desk/Resources/Private/Templates/ToolbarItems']);
         $view->setTemplate($filename);
         $view->getRequest()->setControllerExtensionName('ServiceDesk');
         return $view;
     }
Referenced by ServiceDeskToolbarItem\getDropDown(), and ServiceDeskToolbarItem\getItem().
The documentation for this class was generated from the following file:
/Users/carsten.walther/Development/playground.dev.local/playground.git/typo3conf/ext/jira_service_desk/Classes/Backend/ToolbarItems/ServiceDeskToolbarItem.php