jira_service_desk: ServiceDeskController Class Reference
ServiceDeskController Class Reference
Public Member Functions
indexAction ()
listAction ()
showAction ()
addCommentAction ()
addTransitionAction ()
newAction ()
createAction ()
helpAction ()
accessDeniedAction ()
handle_Request (\Psr\Http\Message\ServerRequestInterface $request)
Protected Member Functions
initializeView (\TYPO3\CMS\Extbase\Mvc\View\ViewInterface $view)
registerDocheaderButtons ()
getLanguageService ()
create_Action (\Psr\Http\Message\ServerRequestInterface $request)
Protected Attributes
$defaultViewObjectName = \TYPO3\CMS\Backend\View\BackendTemplateView::class
$view
$service
$serviceDeskResource
$requestResource
$requesttypeResource
Detailed Description
Definition at line 14 of file ServiceDeskController.php.
Member Function Documentation
initializeView()
initializeView (\TYPO3\CMS\Extbase\Mvc\View\ViewInterface $view) protected
Parameters
\TYPO3\CMS\Extbase\Mvc\View\ViewInterface $view
Returns
void
Exceptions
Definition at line 60 of file ServiceDeskController.php.
     {
         parent::initializeView($view);
         $allowedActionMethods = ['indexAction', 'listAction', 'showAction', 'newAction', 'createAction', 'helpAction', 'accessDeniedAction'];
         if (in_array($this->request->getArguments()['action'], $allowedActionMethods, false)) {
             $this->generateButtons();
             $this->registerDocheaderButtons();
             $this->view->getModuleTemplate()->setFlashMessageQueue($this->controllerContext->getFlashMessageQueue());
         }
         if ($this->view instanceof \TYPO3\CMS\Backend\View\BackendTemplateView) {
             $this->view->getModuleTemplate()->getPageRenderer()->addInlineLanguageLabelFile('EXT:jira_service_desk/Resources/Private/Language/locallang.xlf');
             $this->view->getModuleTemplate()->getPageRenderer()->addCssFile('EXT:jira_service_desk/Resources/Public/Css/backend.css');
             $this->view->getModuleTemplate()->getPageRenderer()->loadRequireJsModule('TYPO3/CMS/JiraServiceDesk/Servicedesk');
         }
         $this->service = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Service::class);
         if ($this->service->initialize()) {
             $this->serviceDeskResource = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\ServiceDesk::class, $this->service);
             $this->requestResource = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\Request::class, $this->service);
             $this->requesttypeResource = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\Requesttype::class, $this->service);
         }
     }
References ServiceDeskController\$view, and ServiceDeskController\registerDocheaderButtons().
Referenced by ServiceDeskController\handle_Request().
indexAction()
indexAction ()
This is the main service desk function an represents the service desk form. With its search it is possible to search help topics in the linked helpdesk/confluence area.
Returns
void
Exceptions
Definition at line 94 of file ServiceDeskController.php.
                                   : void
     {
         $serviceDeskId = (int)$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['jira_service_desk']['serviceDeskId'];
         $requestTypeGroups = $this->serviceDeskResource->getRequestTypeGroup($serviceDeskId);
         $requestTypes = $this->serviceDeskResource->getRequestTypes($serviceDeskId, true);
         foreach ($requestTypeGroups->body->values as $requestTypeGroupKey => $requestTypeGroup) {
             foreach ($requestTypes->body->values as $requestType) {
                 foreach ($requestType->groupIds as $groupId) {
                     if ((int)$groupId === (int)$requestTypeGroup->id) {
                         $requestTypeGroup->requestTypes[] = $requestType;
                     }
                     $requestTypeGroups->body->values[$requestTypeGroupKey] = $requestTypeGroup;
                 }
             }
         }
         $this->view->assignMultiple([
             'serviceDesk' => $this->serviceDeskResource->getServiceDeskById($serviceDeskId),
             'requestTypeGroups' => $requestTypeGroups
         ]);
     }
listAction()
listAction ()
Lists all customer requests.
Returns
void
Exceptions
Definition at line 124 of file ServiceDeskController.php.
                                  : void
     {
         $serviceDeskId = (int)$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['jira_service_desk']['serviceDeskId'];
         $arguments = $this->request->getArguments();
         $filter = $arguments['filter'];
         $requestStatus = $filter['requestStatus'] ?? '';
         $requestOwnership = $filter['requestOwnership'] ?? '';
         $requestTypeId = $filter['requestTypeId'] ?? 0;
         $searchTerm = $filter['searchTerm'] ?? '';
         $approvalStatus = $filter['approvalStatus'] ?? '';
         $page = $arguments['@widget_0']['page'] ?? 0;
         $limit = 10;
         $customerRequests = $this->requestResource->getCustomerRequests($serviceDeskId, (int)$requestTypeId, true, $searchTerm, $requestOwnership, $requestStatus, $approvalStatus, '', (int)$page, $limit);
         $requestTypes = $this->serviceDeskResource->getRequestTypes($serviceDeskId, true);
         $this->view->assignMultiple([
             'page' => $page,
             'limit' => $limit,
             'searchTerm' => $searchTerm,
             'requestOwnership' => $requestOwnership,
             'requestStatus' => $requestStatus,
             'requestTypes' => $requestTypes,
             'requestTypeId' => $requestTypeId,
             'customerRequests' => $customerRequests
         ]);
     }
showAction()
showAction ()
Show the details of a customer requests.
Returns
void
Exceptions
Definition at line 162 of file ServiceDeskController.php.
                                  : void
     {
         $arguments = $this->request->getArguments();
         $comments = $this->requestResource->getRequestComments($arguments['requestId'], true, false);
         $sortedActivities = [];
         foreach ($comments->body->values as $comment) {
             $sortedActivities[$comment->created->epochMillis] = $comment;
         }
         $customerRequest = $this->requestResource->getCustomerRequestByIdOrKey($arguments['requestId'], true);
         foreach ($customerRequest->body->status->values as $state) {
             $sortedActivities[$state->statusDate->epochMillis] = $state;
         }
         krsort($sortedActivities);
         $customerRequest->body->status->values = $sortedActivities;
         $transitions = $this->requestResource->getCustomerTransitions($arguments['requestId']);
         $this->view->assignMultiple([
             'customerRequest' => $customerRequest,
             'transitions' => $transitions
         ]);
     }
addCommentAction()
addCommentAction ()
Add comment fire signal slot and redirect back to show action.
Todo:
Implement attachment upload
Exceptions
Definition at line 197 of file ServiceDeskController.php.
                                        : void
     {
         $arguments = $this->request->getArguments();
         $result = $this->requestResource->createRequestComment($arguments['comment']['requestId'], $arguments['comment']['comment']);
         if ($result->getStatus() === 201) {
             \TYPO3\CMS\Backend\Utility\BackendUtility::setUpdateSignal('ServiceDeskToolbarItem::updateServiceDeskMenu');
             $this->objectManager
                 ->get(\TYPO3\CMS\Core\Messaging\FlashMessageService::class)
                 ->getMessageQueueByIdentifier()
                 ->addMessage(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                     \TYPO3\CMS\Core\Messaging\FlashMessage::class,
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createRequestComment.success.description'),
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createRequestComment.success.title'),
                     \TYPO3\CMS\Core\Messaging\FlashMessage::OK, true
                 ));
         } else {
             $this->objectManager
                 ->get(\TYPO3\CMS\Core\Messaging\FlashMessageService::class)
                 ->getMessageQueueByIdentifier()
                 ->addMessage(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                     \TYPO3\CMS\Core\Messaging\FlashMessage::class,
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createRequestComment.error.description'),
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createRequestComment.error.title'),
                     \TYPO3\CMS\Core\Messaging\FlashMessage::ERROR, true
                 ));
         }
         $this->redirect('show', 'ServiceDesk', null, [
             'requestId' => $arguments['comment']['requestId']
         ]);
     }
References ServiceDeskController\getLanguageService().
addTransitionAction()
addTransitionAction ()
Perform a transition to a customer request, fire signal slot and redirect back to show action.
Todo:
Don't know if it is a good idea to make this here. Currently transitions will be submitted by ajax call in AjaxController.
Exceptions
Definition at line 240 of file ServiceDeskController.php.
                                           : void
     {
         $arguments = $this->request->getArguments();
         $result = $this->requestResource->performCustomerTransition($arguments['transition']['requestId'], (int)$arguments['transition']['transitionId'], $arguments['transition']['comment']);
         if ($result->getStatus() === 204) {
             \TYPO3\CMS\Backend\Utility\BackendUtility::setUpdateSignal('ServiceDeskToolbarItem::updateServiceDeskMenu');
             $this->objectManager
                 ->get(\TYPO3\CMS\Core\Messaging\FlashMessageService::class)
                 ->getMessageQueueByIdentifier()
                 ->addMessage(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                     \TYPO3\CMS\Core\Messaging\FlashMessage::class,
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:performCustomerTransition.success.description'),
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:performCustomerTransition.success.title'),
                     \TYPO3\CMS\Core\Messaging\FlashMessage::OK, true
                 ));
         } else {
             $this->objectManager
                 ->get(\TYPO3\CMS\Core\Messaging\FlashMessageService::class)
                 ->getMessageQueueByIdentifier()
                 ->addMessage(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                     \TYPO3\CMS\Core\Messaging\FlashMessage::class,
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:performCustomerTransition.error.description'),
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:performCustomerTransition.error.title'),
                     \TYPO3\CMS\Core\Messaging\FlashMessage::ERROR, true
                 ));
         }
         $this->redirect('show', 'ServiceDesk', null, [
             'requestId' => $arguments['transition']['requestId']
         ]);
     }
References ServiceDeskController\getLanguageService().
newAction()
newAction ()
Shows the form for new customer requests.
Returns
void
Exceptions
Definition at line 280 of file ServiceDeskController.php.
                                 : void
     {
         $serviceDeskId = (int)$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['jira_service_desk']['serviceDeskId'];
         $arguments = $this->request->getArguments();
         $requestTypes = $this->serviceDeskResource->getRequestTypes($serviceDeskId, true);
         $requestType = [];
         foreach ($requestTypes->body->values as $value) {
             if ($value->id === $arguments['requestTypeId']) {
                 $requestType = $value;
             }
         }
         $this->view->assignMultiple([
             'serviceDesk' => $this->serviceDeskResource->getServiceDeskById($serviceDeskId),
             'requestType' => $requestType,
             'requestTypeFields' => $this->serviceDeskResource->getRequestTypeFields($serviceDeskId, (int)$arguments['requestTypeId']),
             'newCustomerRequest' => $arguments['newCustomerRequest']
         ]);
     }
createAction()
createAction ()
Creates a new customer request.
Exceptions
Definition at line 310 of file ServiceDeskController.php.
                                    : void
     {
         $serviceDeskId = (int)$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['jira_service_desk']['serviceDeskId'];
         $arguments = $this->request->getArguments();
         $formData = [];
         foreach ($arguments['newRequest'] as $key => $value) {
             if (!empty($value)) {
                 if ($key === 'components') {
                     $formData[$key][] = [
                         'id' => $value
                     ];
                 } elseif ($key === 'priority') {
                     $formData[$key] = [
                         'id' => $value
                     ];
                 } else {
                     $formData[$key] = $value;
                 }
             }
         }
         $newRequest = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Domain\Model\Request::class);
         $newRequest->setServiceDeskId($serviceDeskId);
         $newRequest->setRequestTypeId((int)$arguments['requestType']['id']);
         $allowedFields = ['summary', 'components', 'priority', 'description', 'duedate'];
         foreach ($formData as $key => $value) {
             if ($value && in_array($key, $allowedFields, true)) {
                 $newRequest->setRequestCustomField($key, $value);
             }
         }
         $result = $this->requestResource->createCustomerRequest($newRequest);
         if ($result->getStatus() === 201) {
             \TYPO3\CMS\Backend\Utility\BackendUtility::setUpdateSignal('ServiceDeskToolbarItem::updateServiceDeskMenu');
             $this->objectManager
                 ->get(\TYPO3\CMS\Core\Messaging\FlashMessageService::class)
                 ->getMessageQueueByIdentifier()
                 ->addMessage(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                     \TYPO3\CMS\Core\Messaging\FlashMessage::class,
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createCustomerRequest.success.description'),
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createCustomerRequest.success.title'),
                     \TYPO3\CMS\Core\Messaging\FlashMessage::OK, true
                 ));
             $this->redirect('show', 'ServiceDesk', null, [
                 'requestId' => $result->body->issueId
             ]);
         } else {
             $this->objectManager
                 ->get(\TYPO3\CMS\Core\Messaging\FlashMessageService::class)
                 ->getMessageQueueByIdentifier()
                 ->addMessage(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
                     \TYPO3\CMS\Core\Messaging\FlashMessage::class,
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createCustomerRequest.error.description'),
                     $this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:createCustomerRequest.error.title'),
                     \TYPO3\CMS\Core\Messaging\FlashMessage::ERROR, true
                 ));
             $this->redirect('index', 'ServiceDesk');
         }
     }
References ServiceDeskController\getLanguageService().
Referenced by ServiceDeskController\handle_Request().
helpAction()
helpAction ()
Show the help.
Returns
void
Definition at line 380 of file ServiceDeskController.php.
                                  : void
     {
     }
Referenced by ServiceDeskController\handle_Request().
accessDeniedAction()
accessDeniedAction ()
Shows the access denied message.
Returns
void
Definition at line 390 of file ServiceDeskController.php.
                                          : void
     {
     }
Referenced by ServiceDeskController\handle_Request().
registerDocheaderButtons()
registerDocheaderButtons () protected
Generate the DocheaderButtons
Returns
void
Exceptions
Definition at line 401 of file ServiceDeskController.php.
                                                   : void
     {
         $uriBuilder = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Backend\Routing\UriBuilder::class);
         $getVars = $this->request->getArguments();
         $menu = $this->view->getModuleTemplate()->getDocHeaderComponent()->getMenuRegistry()->makeMenu();
         $menu->setIdentifier('WebFuncJumpMenu');
         $menuItem = $menu
             ->makeMenuItem()
             ->setHref($uriBuilder->buildUriFromRoute('help_JiraServiceDeskJira', ['action' => 'index']))
             ->setTitle($this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:serviceDesk.menu.serviceDesk.title'))
             ->setActive($getVars['action'] === 'serviceDesk');
         $menu->addMenuItem($menuItem);
         $menuItem = $menu
             ->makeMenuItem()
             ->setHref($uriBuilder->buildUriFromRoute('help_JiraServiceDeskJira', ['action' => 'list']))
             ->setTitle($this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:serviceDesk.menu.requests.title'))
             ->setActive($getVars['action'] === 'requests');
         $menu->addMenuItem($menuItem);
         $menuItem = $menu
             ->makeMenuItem()
             ->setHref($uriBuilder->buildUriFromRoute('help_JiraServiceDeskJira', ['action' => 'help']))
             ->setTitle($this->getLanguageService()->sL('LLL:EXT:jira_service_desk/Resources/Private/Language/locallang.xlf:serviceDesk.menu.help.title'))
             ->setActive($getVars['action'] === 'help');
         $menu->addMenuItem($menuItem);
         $this->view->getModuleTemplate()->getDocHeaderComponent()->getMenuRegistry()->addMenu($menu);
     }
References ServiceDeskController\getLanguageService().
Referenced by ServiceDeskController\initializeView().
getLanguageService()
getLanguageService () protected
Returns LanguageService
Returns
\TYPO3\CMS\Core\Localization\LanguageService
Definition at line 457 of file ServiceDeskController.php.
                                             : \TYPO3\CMS\Core\Localization\LanguageService
     {
         return $GLOBALS['LANG'];
     }
Referenced by ServiceDeskController\addCommentAction(), ServiceDeskController\addTransitionAction(), ServiceDeskController\createAction(), and ServiceDeskController\registerDocheaderButtons().
handle_Request()
handle_Request (\Psr\Http\Message\ServerRequestInterface $request)
Handles the requests and loads the resolved action for the backend module.
Parameters
\Psr\Http\Message\ServerRequestInterface $request
Returns
\Psr\Http\Message\ResponseInterface
Exceptions
Definition at line 487 of file ServiceDeskController.php.
                                                                                       : \Psr\Http\Message\ResponseInterface
     {
         $this->action = $request->getQueryParams()['tx_servicedesk_']['action'] ?: 'serviceDesk';
         if (!\Walther\JiraServiceDesk\Utility\AccessUtility::hasAccess()) {
             $this->action = 'accessDenied';
         } else {
             $this->generateMenu();
             $this->generateButtons();
         }
         $this->initializeView($this->action);
         switch ($this->action) {
             default:
                 $this->accessDeniedAction();
                 break;
             case 'serviceDesk':
                 $this->serviceDeskAction($request);
                 break;
             case 'create':
                 $this->createAction($request);
                 break;
             case 'requests':
                 $this->requestsAction($request);
                 break;
             case 'request':
                 $this->requestAction($request);
                 break;
             case 'help':
                 $this->helpAction();
                 break;
         }
         return new \TYPO3\CMS\Core\Http\HtmlResponse($this->view->getModuleTemplate()->setContent($this->view->render())->renderContent());
     }
References ServiceDeskController\accessDeniedAction(), ServiceDeskController\createAction(), ServiceDeskController\helpAction(), and ServiceDeskController\initializeView().
create_Action()
create_Action (\Psr\Http\Message\ServerRequestInterface $request) protected
Handles the create functions for new customer requests.
Parameters
\Psr\Http\Message\ServerRequestInterface $request
Returns
mixed
Exceptions
Definition at line 541 of file ServiceDeskController.php.
     {
         $serviceDeskId = (int)$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['jira_service_desk']['serviceDeskId'];
         $serviceDesk = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\ServiceDesk::class, $this->service);
         $requestType = $request->getQueryParams()['tx_servicedesk_']['requestType'];
         $parsedBody = $request->getParsedBody()['newRequest'];
         $formData = [];
         if (is_array($parsedBody)) {
             foreach ($parsedBody as $key => $value) {
                 if ($key === 'components') {
                     if (is_array($value)) {
                         foreach ($value as $component) {
                             $formData[$key][] = [
                                 'id' => $component
                             ];
                         }
                     }
                 } else if ($key === 'priority') {
                     $formData[$key] = [
                         'id' => $value
                     ];
                 } else {
                     $formData[$key] = $value;
                 }
             }
             $allowedFields = ['summary', 'components', 'priority', 'description', 'duedate'];
             $newRequest = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Domain\Model\Request::class);
             $newRequest->setServiceDeskId($serviceDeskId);
             $newRequest->setRequestTypeId((int)$requestType['id']);
             foreach ($formData as $key => $value) {
                 if ($value && in_array($key, $allowedFields, true)) {
                     $newRequest->setRequestCustomField($key, $value);
                 }
             }
             \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\Walther\JiraServiceDesk\Service\Resource\Request::class, $this->service)->createCustomerRequest($newRequest);
             \TYPO3\CMS\Backend\Utility\BackendUtility::setUpdateSignal('ServiceDeskToolbarItem::updateServiceDeskMenu');
             #return new \TYPO3\CMS\Core\Http\RedirectResponse(\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Backend\Routing\UriBuilder::class)->buildUriFromRoute('help_JiraServiceDesk', ['tx_servicedesk_' => ['action' => 'serviceDesk']]));
         }
         $this->view->assignMultiple([
             'requestType' => $requestType,
             'data' => $serviceDesk->getRequestTypeFields($serviceDeskId, (int)$requestType['id'])
         ]);
     }
Field Documentation
$defaultViewObjectName
$defaultViewObjectName = \TYPO3\CMS\Backend\View\BackendTemplateView::class protected
Definition at line 19 of file ServiceDeskController.php.
$view
$view protected
Definition at line 24 of file ServiceDeskController.php.
Referenced by ServiceDeskController\initializeView().
$service
$service protected
Definition at line 31 of file ServiceDeskController.php.
$serviceDeskResource
$serviceDeskResource protected
Definition at line 38 of file ServiceDeskController.php.
$requestResource
$requestResource protected
Definition at line 45 of file ServiceDeskController.php.
$requesttypeResource
$requesttypeResource protected
Definition at line 52 of file ServiceDeskController.php.
The documentation for this class was generated from the following file:
/Users/carsten.walther/Development/playground.dev.local/playground.git/typo3conf/ext/jira_service_desk/Classes/Controller/ServiceDeskController.php