var namespace_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget =
[
    [ "Controller", "namespace_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget_1_1_controller.html", "namespace_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget_1_1_controller" ],
    [ "PaginateViewHelper", "class_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget_1_1_paginate_view_helper.html", "class_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget_1_1_paginate_view_helper" ]
];