var namespace_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget_1_1_controller =
[
    [ "PaginateController", "class_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget_1_1_controller_1_1_paginate_controller.html", "class_walther_1_1_jira_service_desk_1_1_view_helpers_1_1_be_1_1_widget_1_1_controller_1_1_paginate_controller" ]
];